name: mds_ansible_gateway_teardown

secrets:
  cloud_provider:
    file: ./secrets/cloud_provider
  cloud_provider_api_key:
    file: ./secrets/cloud_provider_api_key
  gateway_firewall_group_description:
    file: ./secrets/gateway_firewall_group_description
  gateway_instance_label:
    file: ./secrets/gateway_instance_label
  gateway_ssh_key_name:
    file: ./secrets/gateway_ssh_key_name

services:
  ansible_gateway_teardown:
    build:
      context: ./ansible_container
    command: ["teardown"]
    secrets:
      - cloud_provider
      - cloud_provider_api_key
      - gateway_firewall_group_description
      - gateway_instance_label
      - gateway_ssh_key_name
