- name: Create gateway SSH key pair
  hosts: control_nodes
  gather_facts: false
  roles:
    - role: config
    - role: ssh_key_pair
      vars:
        ssh_key_comment: '{{ gateway_ssh_key_comment }}'
        ssh_key_path: '{{ gateway_ssh_key_path }}'
  vars_files:
    - config.yml

- name: Provision gateway
  hosts: control_nodes
  gather_facts: false
  roles:
    - gateway_provisioning
  vars_files:
    - config.yml
