name: mds_gateway_provision

secrets:
  cloud_provider:
    file: ./secrets/cloud_provider
  cloud_provider_api_key:
    file: ./secrets/cloud_provider_api_key
  gateway_control_node_ips:
    file: ./secrets/gateway_control_node_ips
  gateway_firewall_group_description:
    file: ./secrets/gateway_firewall_group_description
  gateway_hostname:
    file: ./secrets/gateway_hostname
  gateway_instance_label:
    file: ./secrets/gateway_instance_label
  gateway_ssh_key_name:
    file: ./secrets/gateway_ssh_key_name
  gateway_ssh_key_public:
    file: ./secrets/gateway_ssh_key_public

services:
  ansible_gateway_provision:
    build:
      context: ./ansible_container
    command: ["provision"]
    secrets:
      - cloud_provider
      - cloud_provider_api_key
      - gateway_control_node_ips
      - gateway_firewall_group_description
      - gateway_hostname
      - gateway_instance_label
      - gateway_ssh_key_name
      - gateway_ssh_key_public
    volumes:
      # To generate the known_hosts file used by the setup playbook.
      - ./ansible_data/.ssh:/home/ansible/.ssh
