argument_specs:
  main:
    options:
      control_node_ips:
        elements: str
        required: true
        short_description: The IP addresses, IPv4 and IPv6, of the Ansible control node(s).
        type: list
      gateway_firewall_group_name:
        short_description: Unique identifier for the gateway's firewall group on the cloud provider.
        required: true
        type: str
      gateway_hostname:
        short_description: The fully qualified domain name (FQDN) of the gateway.
        required: true
        type: str
      gateway_instance_name:
        short_description: The unique instance name for identifying the gateway on the cloud provider.
        required: true
        type: str
      gateway_instance_region:
        short_description: Region to provision gateway instance.
        required: true
        type: str
      gateway_provider:
        options:
          name:
            choices:
              - vultr
            required: true
            type: str
          vultr_api_key:
            short_description: Vultr API key, generated in Vultr dashboard.
            type: str
        required_if:
          - ['name', 'vultr', ['vultr_api_key']]
        required: true
        short_description: The cloud provider to use to host the gateway server.
        type: dict
      gateway_ssh_key_comment:
        default: Minecraft Docker Stack Gateway
        short_description: The comment argument provided to the SSH key command.
        type: str
      gateway_ssh_key_name:
        required: true
        short_description: The name of the gateway SSH key on the cloud provider.
        type: str
      gateway_ssh_key_path:
        default: '{{ secrets_folder }}/gateway_ssh_key'
        description: >-
          The path to save the gateway SSH key.

          This is the path to the private key. Its containing folder will be
          created to hold this key and its associated public key.
        short_description: The path to save the gateway SSH key.
        type: path
      secrets_folder:
        default: '{{ playbook_dir }}/secrets'
        description: >-
          The path to a folder to write local secrets.

          Things like generated SSH keys will be written here.
        short_description: The path to a folder to write local secrets.
        type: path
      server_ips:
        elements: str
        required: true
        short_description: The IPs, IPv4 and IPv6, of the server node.
        type: list
      timezone:
        required: true
        short_description: 'The Linux timezone. Example: America/New_York'
        type: str
