- name: Provision gateway instance
  hosts: localhost
  gather_facts: false
  vars:
    api_key:                    '{{ lookup("ansible.builtin.file", "/run/secrets/cloud_provider_api_key") }}'
    firewall_group_description: '{{ lookup("ansible.builtin.file", "/run/secrets/gateway_firewall_group_description") }}'
    hostname:                   '{{ lookup("ansible.builtin.file", "/run/secrets/gateway_hostname") }}'
    instance_label:             '{{ lookup("ansible.builtin.file", "/run/secrets/gateway_instance_label") }}'
    ssh_key_name:               '{{ lookup("ansible.builtin.file", "/run/secrets/gateway_ssh_key_name") }}'
  tasks:
    - name: Provision instance
      vultr.cloud.instance:
        api_key: '{{ api_key }}'
        backups: false
        ddos_protection: false
        enable_ipv6: true
        firewall_group: "{{ firewall_group_description }}"
        hostname: "{{ hostname }}"
        label: "{{ instance_label }}"
        os: Debian 12 x64 (bookworm)
        plan: vc2-1c-1gb
        region: atl
        ssh_keys:
          - "{{ ssh_key_name }}"
        state: started
      register: cloud_instance_response

    - name: Wait for SSH to come up on the gateway
      ansible.builtin.wait_for:
        host: "{{ cloud_instance_response.vultr_instance.main_ip }}"
        port: 22
        sleep: 5

    - name: Write key to known_hosts
      shell: "ssh-keyscan -H {{ cloud_instance_response.vultr_instance.main_ip }} > /home/ansible/.ssh/known_hosts"
