- name: Provision gateway instance, firewall group, and SSH key on Vultr.
  hosts: localhost
  gather_facts: false
  vars:
    api_key_file: "{{ lookup('ansible.builtin.env', 'CLOUD_PROVIDER_API_KEY_FILE') }}"
    api_key: "{{ lookup('ansible.builtin.file', '{{ api_key_file }}') }}"
  tasks:
    - name: Fetch the list of SSH keys.
      vultr.cloud.ssh_key_info:
        api_key: "{{ api_key }}"
      register: vultr_ssh_keys

    # TODO: Add additional provisioning steps.
    - name: List SSH keys.
      ansible.builtin.debug:
        var: vultr_ssh_keys
