- name: Filter hosts by gateway instance label
  hosts: all
  gather_facts: false
  run_once: true
  vars:
    instance_label: '{{ lookup("ansible.builtin.file", "/run/secrets/gateway_instance_label") }}'
  tags:
    - tunnel-keys
  tasks:
    - name: Add hosts to group matching gateway instance label
      ansible.builtin.add_host:
        name: '{{ item }}'
        groups: gateways
      loop: '{{ ansible_play_hosts }}'
      when: item == instance_label

- name: Generate tunnel public and private keys
  hosts: gateways
  tags: tunnel-keys
  tasks:
    - name: Create folder for tunnel_host SSH keys
      ansible.builtin.file:
        group: '1000'
        mode: '700'
        owner: '1000'
        path: /opt/tunnel_host
        state: directory

    - name: Generate host SSH key pair
      community.crypto.openssh_keypair:
        backend: opensshbin
        comment: 'Tunnel Host'
        group: '1000'
        mode: '400'
        owner: '1000'
        path: /opt/tunnel_host/ssh_host_ed25519_key
        state: present
        type: ed25519
      register: ssh_keypair

    - name: Create folder for tunnel_client SSH keys
      ansible.builtin.file:
        group: "1000"
        mode: "700"
        owner: "1000"
        path: /tunnel_client_data/.ssh
        state: directory
      delegate_to: localhost

    - name: Add host key to client's known_hosts file
      ansible.builtin.copy:
        content: >
          {{ ansible_host }} {{ ssh_keypair.public_key }}
        dest: /tunnel_client_data/.ssh/known_hosts
        directory_mode: "700"
        group: "1000"
        mode: "400"
        owner: "1000"
      delegate_to: localhost

    # TODO: Use community.crypto.openssh_keypair once this issue is addressed:
    # The module attempts to set attributes on created files which is not
    # supported on the volumes mounted by Docker.
    # https://github.com/ansible-collections/community.crypto/issues/416
    # https://github.com/ansible/ansible/issues/77217
    # - name: Generate client SSH key pair
    #   community.crypto.openssh_keypair:
    #     attributes: '-a'
    #     backend: opensshbin
    #     comment: 'Tunnel Client'
    #     group: '1000'
    #     mode: '400'
    #     owner: '1000'
    #     path: /tunnel_client_data/.ssh/id_ed25519
    #     state: present
    #     type: ed25519
    #   delegate_to: localhost
    - name: Use workaround to generate client SSH key pair
      block:
        - name: Create client SSH key pair
          ansible.builtin.command:
            cmd: ssh-keygen -t ed25519 -f /tunnel_client_data/.ssh/id_ed25519 -N "" -C "Tunnel Client"
            creates: /tunnel_client_data/.ssh/id_ed25519
          delegate_to: localhost

        - name: Set permissions on client SSH key pair
          ansible.builtin.file:
            group: '1000'
            mode: '400'
            owner: '1000'
            path: '{{ "/tunnel_client_data/.ssh/" + item }}'
            state: file
          loop:
            - id_ed25519
            - id_ed25519.pub
          delegate_to: localhost

    - name: Add client key to host's authorized_keys
      ansible.builtin.copy:
        dest: /opt/tunnel_host/authorized_keys
        group: '1000'
        mode: '400'
        owner: '1000'
        src: /tunnel_client_data/.ssh/id_ed25519.pub
