- name: Print SSH key path
  ansible.builtin.debug:
    var: gateway_ssh_key_path

- name: Create folder for SSH key pair
  ansible.builtin.file:
    path: '{{ gateway_ssh_key_path | ansible.builtin.dirname }}'
    state: directory

- name: Create SSH key pair
  community.crypto.openssh_keypair:
    backend: opensshbin
    comment: '{{ gateway_ssh_key_comment }}'
    path: '{{ gateway_ssh_key_path }}'
    state: present
    type: ed25519
  register: openssh_keypair_result

- name: Set fact for SSH public key
  ansible.builtin.set_fact:
    gateway_ssh_key_public: '{{ openssh_keypair_result.public_key }}'
