- name: Ensure IPv6 is enabled with a prefix length of 64
  ansible.builtin.assert:
    that: 'ansible_default_ipv6.prefix == "64"'

# Configure Docker:
# - Set logging driver to json logger.
# - Enable automatic log rotation.
# - Enable IPv6.
# https://docs.docker.com/engine/install/linux-postinstall/#configure-default-logging-driver
# https://docs.docker.com/engine/logging/drivers/json-file/
# https://docs.docker.com/engine/daemon/ipv6/
- name: Write Docker daemon.json
  ansible.builtin.template:
    dest: /etc/docker/daemon.json
    group: root
    mode: '400'
    owner: root
    src: docker_daemon_json.j2
  notify: Restart Docker
