- name: Set fact for Docker keyring path
  ansible.builtin.set_fact:
    docker_keyring_path: /etc/apt/keyrings/docker.asc

- name: Add Docker GPG key
  ansible.builtin.get_url:
    dest: '{{ docker_keyring_path }}'
    group: root
    mode: '444'
    owner: root
    url: https://download.docker.com/linux/debian/gpg

- name: Configure Docker apt repository
  ansible.builtin.apt_repository:
    filename: docker.list
    repo: >-
      deb
      [arch=amd64 signed-by={{ docker_keyring_path }}]
      https://download.docker.com/linux/debian bookworm stable

- name: Install Docker packages
  ansible.builtin.apt:
    cache_valid_time: 3_600 # 60 minutes.
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
