- name: Import tasks for general configurations
  ansible.builtin.import_tasks: apply_general_configurations.yml

- name: Import tasks for installing Docker
  ansible.builtin.import_tasks: install_docker.yml

- name: Import tasks for configuring Docker
  ansible.builtin.import_tasks: configure_docker.yml
  tags: configure_docker

- name: Import tasks for deploying Docker services
  ansible.builtin.import_tasks: deploy_docker_services.yml
  tags: deploy_docker_services

- name: Import tasks to configure Docker context
  ansible.builtin.import_tasks: configure_docker_context.yml
  delegate_to: localhost
  tags: configure_docker_context
